os:
  - linux

language: python

#python:
##  - '3.5'
#  - '3.6'
#  - '3.7'

jdk:
  - oraclejdk8
  - openjdk8

cache:
  directories:
  - $HOME/.m2

env:
  global:
    - PYTHON=python
    - PIP=pip
    - INST="--no-binary JPype1"

#addons:
#  apt:
#    packages:
#    - protobuf-compiler

matrix:
  include:
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
      dist: xenial
      language: python

    - name: "Python 3.6 on Xenial Linux"
      python: 3.6
      dist: xenial
      language: python

    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode10.2
      language: java
      env:
        - PYTHON=python3
        - INST="--user --no-binary JPype1"
        - PIP=pip3


# for manual installation of protoc. Needed for proto3 format...
before_install:
  - export PATH=$HOME/protobuf/bin:$PATH
  - export C_INCLUDE_PATH=$C_INCLUDE_PATH:$HOME/protobuf/include
  - export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$HOME/protobuf/include

install:
  - mkdir -p $HOME/protobuf && pushd $HOME/protobuf &&
    curl -LO 'https://github.com/google/protobuf/releases/download/v3.6.0/protoc-3.6.0-linux-x86_64.zip' &&
    unzip protoc-3.6.0-linux-x86_64.zip &&
    popd
  - make python_dist PYTHON=$PYTHON
  - $PIP install -v $INST dist/*

script:
  - $PYTHON -c "import pythonmatsim"
  - $PYTHON -m unittest test/*_test.py

deploy:
    provider: pypi
    user: "tduberne"
    password:
        secure: NjK880lxiHeBlJv7ZurckChh65VYpWRj96f6jGI7I89JZ+ujXo9a2D0ijwj7F9PrIXm6QeUbYzCE1/at8WxAnDAuQzuRZ8gzVvPFX4VaN9fIQWyhkJNyWaXyMvc7D9zFCO5rM0n//uafRDmSQTMNUH1E50nZ7LRdbenuHKDRoAnsHe4e0s7z5+Rh80Vho6ly4Y0/N0dCeTIg8uAXeuhPMbPvYZZhR6qL1mNaf2whUA/5H/kM0NnP+fXIBoN/GFWyp4T3rInv2Gj1Y8BvK5ZeF4/jSxRuD61vYgjDgpEYLrAt8PuJLjqOFegnATVv+npwpAgMueCgb8BeyyVKVforA2ePBqbjSqKzatmFAlNE1lQEfZ0emSVPhwHbG8695RrRBNCGNUngDMKPFpH5pNquAyC8wKP8ZW7bqtCJsxOn0YEq6tO00plPoXTq1tfhixl7ieJddqfyFCyTQ3RorPGJjs8pyX2fmPlZmtST77JkP1RVpou76/XihTwB6bq4Bbd/cmONUY53u+BPQHigIsDpLTkt+cabcuL7zBnSHh0sbLqTklicNIYhJPDeVtKVv1NpQJR84vxitBw6QQgL7AVKJlO2a3Ilr8UKRFxV/MUpUDZSedeyOesQrsDSaj/cs6lqOIIJka7bTHHbUHuOEHP7qOhcnGPJwJrXCmx/3zrDfxI=
    on:
        tags: true
    skip_existing: true
    skip_cleanup: true
